apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      exemplarTraceIdDestinations:
        - datasourceUid: jaeger
          name: trace_id
  - name: Jaeger
    uid: jaeger
    type: jaeger
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: prometheus
